In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2016, 9895, 1593, 3823],
 [2016, 9895, 1593, 8481],
 [2016, 6585, 1593, 5970],
 [6225, 8732, 9965, 4944, 5042],
 [6225, 8732, 9965, 4944, 1647],
 [8186, 2016, 2570, 1593, 1409],
 [4766, 2765, 7106, 4944]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2016 9895 1593 3823]
 [   0    0    0    0 2016 9895 1593 8481]
 [   0    0    0    0 2016 6585 1593 5970]
 [   0    0    0 6225 8732 9965 4944 5042]
 [   0    0    0 6225 8732 9965 4944 1647]
 [   0    0    0 8186 2016 2570 1593 1409]
 [   0    0    0    0 4766 2765 7106 4944]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

C:\Users\mitta\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [18]:
predictions = model.predict(embedded_docs)
print(predictions)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
[[[ 0.042543   -0.04629235  0.01099119  0.02340526 -0.03463521
    0.00284793 -0.0265221   0.04007322  0.00047313  0.04795085]
  [ 0.042543   -0.04629235  0.01099119  0.02340526 -0.03463521
    0.00284793 -0.0265221   0.04007322  0.00047313  0.04795085]
  [ 0.042543   -0.04629235  0.01099119  0.02340526 -0.03463521
    0.00284793 -0.0265221   0.04007322  0.00047313  0.04795085]
  [ 0.042543   -0.04629235  0.01099119  0.02340526 -0.03463521
    0.00284793 -0.0265221   0.04007322  0.00047313  0.04795085]
  [ 0.00786592 -0.04989188  0.02330983 -0.04306471  0.01320329
   -0.00771997 -0.0415301  -0.04424826  0.02050379  0.03195905]
  [-0.04853103  0.0211802  -0.04214178  0.02744857  0.00803969
    0.01239993  0.01252708 -0.03548961  0.03655067 -0.04976171]
  [-0.02954904 -0.03585329  0.00017063 -0.00509658  0.04583636
   -0.01449013 -0.01390699  0.00137608 -0.01042248  0.00645934]
  [ 0.02562344  0.00990539  0.02676752  0.01839758  0.02290065
    0.0045

In [22]:
embedded_docs[0].reshape(1,-1)

array([[   0,    0,    0,    0, 2016, 9895, 1593, 3823]])

In [21]:
single_prediction = model.predict(embedded_docs[0].reshape(1,-1))
print(single_prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
[[[ 0.042543   -0.04629235  0.01099119  0.02340526 -0.03463521
    0.00284793 -0.0265221   0.04007322  0.00047313  0.04795085]
  [ 0.042543   -0.04629235  0.01099119  0.02340526 -0.03463521
    0.00284793 -0.0265221   0.04007322  0.00047313  0.04795085]
  [ 0.042543   -0.04629235  0.01099119  0.02340526 -0.03463521
    0.00284793 -0.0265221   0.04007322  0.00047313  0.04795085]
  [ 0.042543   -0.04629235  0.01099119  0.02340526 -0.03463521
    0.00284793 -0.0265221   0.04007322  0.00047313  0.04795085]
  [ 0.00786592 -0.04989188  0.02330983 -0.04306471  0.01320329
   -0.00771997 -0.0415301  -0.04424826  0.02050379  0.03195905]
  [-0.04853103  0.0211802  -0.04214178  0.02744857  0.00803969
    0.01239993  0.01252708 -0.03548961  0.03655067 -0.04976171]
  [-0.02954904 -0.03585329  0.00017063 -0.00509658  0.04583636
   -0.01449013 -0.01390699  0.00137608 -0.01042248  0.00645934]
  [ 0.02562344  0.00990539  0.02676752  0.01839758  0.02290065
    0.0045